= Iricom Backend
REST API
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

== 서버
=== 정보 조회
서버의 버전 및 상태 조회

operation::SERVER_INFO[snippets='curl-request,http-response,response-fields']

== 계정

=== 내 정보 조회
==== IF_001
operation::IF_001[snippets='curl-request,http-response,response-fields']

=== 계정 목록 조회
==== AC_001
계정 목록 조회, 페이지네이션, 키워드를 지원

operation::AC_001[snippets='curl-request,request-parameters,http-response,response-fields']

=== 계정 정보 조회
==== AC_002
특정 계정의 정보 조회

operation::AC_002[snippets='curl-request,path-parameters,http-response,response-fields']

=== 계정 정보 수정
==== AC_003
자신의 정보 수정

operation::AC_003[snippets='curl-request,request-fields,http-response,response-fields']

=== 계정 정보 수정
==== AC_004
다른 계정의 정보 수정

operation::AC_004[snippets='curl-request,path-parameters,request-fields,http-response,response-fields']

== 게시판

=== 게시판 생성
==== BD_001
새로운 게시판을 생성

operation::BD_001[snippets='curl-request,request-fields,http-response,response-fields']

=== 게시판 목록 조회
==== BD_002
게시판 목록 조회, 페이지네이션, 키워드를 지원

operation::BD_002[snippets='curl-request,request-parameters,http-response,response-fields']

=== 게시판 정보 조회
==== BD_003
게시판 정보 조회

operation::BD_003[snippets='curl-request,path-parameters,http-response,response-fields']

=== 게시판 수정
==== BD_004
게시판 정보 수정

operation::BD_004[snippets='curl-request,path-parameters,request-fields,http-response,response-fields']
