= Iricom Backend
REST API
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

== 서버
=== 정보 조회
서버의 버전 및 상태 조회

operation::SERVER_INFO[snippets='curl-request,http-response,response-fields']

== 내 정보

=== 내 정보 조회
==== IF_001
operation::IF_001[snippets='curl-request,http-response,response-fields']

=== 내가 작성한 문서 조회
==== IF_002
operation::IF_002[snippets='curl-request,request-parameters,http-response,response-fields']

== 계정

=== 계정 목록 조회
==== AC_001
계정 목록 조회, 페이지네이션, 키워드 검색을 지원

operation::AC_001[snippets='curl-request,request-parameters,http-response,response-fields']

=== 계정 정보 조회
==== AC_002
특정 계정의 정보 조회

operation::AC_002[snippets='curl-request,path-parameters,http-response,response-fields']

=== 계정 정보 수정
==== AC_003
자신의 정보 수정

operation::AC_003[snippets='curl-request,request-fields,http-response,response-fields']

=== 계정 정보 수정
==== AC_004
다른 계정의 정보 수정

operation::AC_004[snippets='curl-request,path-parameters,request-fields,http-response,response-fields']

== 게시판

=== 게시판 생성
==== BD_001
새로운 게시판을 생성

operation::BD_001[snippets='curl-request,request-fields,http-response,response-fields']

=== 게시판 목록 조회
==== BD_002
게시판 목록 조회, 페이지네이션, 키워드 검색을 지원

operation::BD_002[snippets='curl-request,request-parameters,http-response,response-fields']

=== 게시판 정보 조회
==== BD_003
게시판 정보 조회

operation::BD_003[snippets='curl-request,path-parameters,http-response,response-fields']

=== 게시판 수정
==== BD_004
게시판 정보 수정

operation::BD_004[snippets='curl-request,path-parameters,request-fields,http-response,response-fields']

== 게시물

=== 게시물 생성
==== PS_001
게시물 생성

operation::PS_001[snippets='curl-request,path-parameters,request-fields,http-response,response-fields']

=== 게시물 목록 조회
==== PS_002
게시물 목록 조회, 페이지네이션, 키워드 검색을 지원

operation::PS_002[snippets='curl-request,path-parameters,request-parameters,http-response,response-fields']

=== 게시물 정보 조회
==== PS_003
게시물 정보 조회

operation::PS_003[snippets='curl-request,path-parameters,request-parameters,http-response,response-fields']

=== 게시물 수정
==== PS_004
게시물 수정

operation::PS_004[snippets='curl-request,path-parameters,request-fields,http-response,response-fields']

=== 게시물 발행
==== PS_005

operation::PS_005[snippets='curl-request,path-parameters,http-response,response-fields']

=== 게시물 삭제
==== PS_006

operation::PS_006[snippets='curl-request,path-parameters,http-response,response-fields']

=== 게시물 좋아요/싫어요
==== PS_007

operation::PS_007[snippets='curl-request,path-parameters,request-fields,http-response,response-fields']

== 댓글

=== 댓글 생성
==== CM_001

operation::CM_001[snippets='curl-request,path-parameters,request-fields,http-response,response-fields']

=== 댓글 목록 조회
==== CM_002

operation::CM_002[snippets='curl-request,path-parameters,request-parameters,http-response,response-fields']

=== 댓글 수정
==== CM_003

operation::CM_003[snippets='curl-request,path-parameters,request-fields,http-response,response-fields']

=== 댓글 삭제
==== CM_004

operation::CM_004[snippets='curl-request,path-parameters,http-response,response-fields']

=== 댓글 좋이요/싫어요
==== CM_005

operation::CM_005[snippets='curl-request,path-parameters,request-fields,http-response,response-fields']

== 게시판 관리자

=== 게시판 관리자 생성
==== AT_001

operation::AT_001[snippets='curl-request,request-fields,http-response']

=== 게시판 관리자 목록 조회
==== AT_002

operation::AT_002[snippets='curl-request,request-parameters,http-response,response-fields']

=== 게시판 관리자 조회
==== AT_003

operation::AT_003[snippets='curl-request,path-parameters,http-response,response-fields']


=== 게시판 관리자 삭제
==== AT_004

operation::AT_004[snippets='curl-request,request-fields,http-response']

== 신고
=== 게시물 신고
==== RP_001

operation::RP_001[snippets='curl-request,request-fields,http-response']
