# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build, Test

on:
  push:
    branches: [ "pre-production" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Make iricom-server firebase-adminsdk.json for JUnit
      run: |
        cd ./iricom-server/src/test/resources
        touch ./firebase-adminsdk.json
        echo "${{ secrets.TEST_FIREBASE_ADMIN_ADK }}" > ./firebase-adminsdk.json
      shell: bash

    - name: Make iricom-storage firebase-adminsdk.json for JUnit
      run: |
        cd ./iricom-storage/src/test/resources
        touch ./firebase-adminsdk.json
        echo "${{ secrets.TEST_FIREBASE_ADMIN_ADK }}" > ./firebase-adminsdk.json
      shell: bash

    - name: Make iricom-storage/iricom-storage-file firebase-adminsdk.json for JUnit
      run: |
        cd ./iricom-storage/iricom-storage-file/src/test/resources
        touch ./firebase-adminsdk.json
        echo "${{ secrets.TEST_FIREBASE_ADMIN_ADK }}" > ./firebase-adminsdk.json
      shell: bash

    - name: Make iricom-storage/iricom-storage-s3 firebase-adminsdk.json for JUnit
      run: |
        cd ./iricom-storage/iricom-storage-s3/src/test/resources
        touch ./firebase-adminsdk.json
        echo "${{ secrets.TEST_FIREBASE_ADMIN_ADK }}" > ./firebase-adminsdk.json
      shell: bash

    - name: Make iricom-storage/iricom-storage-s3 application.yml for JUnit
      run: |
        cd ./iricom-storage/iricom-storage-s3/src/test/resources
        touch ./firebase-adminsdk.json
        echo "${{ secrets.TEST_MINIO_APPLICATION_YML }}" > ./application.yml
      shell: bash

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
